### ISSUE TITLE
Toast messages works on the android emulator only.

### ISSUE THREAD

**Issue by noo-shell** [Pulimet/Toaster-Library#1]
Tested on API in versions 16, 26, 27, but works only on the android emulator.
Phones and tablets do not display messages or even custom_layout.xml view.

Scenario
Click on following buttons:
1. [SHOW TOAST]
2. [CUSTOM TOAST]

**Comment by noo-shell** [comment]
The problem is how you use
ObjectAnimator fadeOut = ObjectAnimator.ofFloat(layout, "alpha", 1f, 0f);
I have disabled animations on all devices, so nothing will show up.

https://lifehacker.com/disable-animations-on-android-to-improve-performance-1583554900

https://developer.android.com/reference/android/animation/ValueAnimator.html
> This can change if either the user sets a Developer Option to set the animator duration scale to 0 **or by Battery Savery mode being enabled (which disables all animations).**

You can use this and Runnable for androids with disabled animations
>    private static float getSystemAnimationsDuration(Context context) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
            return Settings.Global.getFloat(
                    context.getContentResolver(),
                    Settings.Global.ANIMATOR_DURATION_SCALE,
                    0);
        } else {
            return Settings.System.getFloat(
                    context.getContentResolver(),
                    Settings.System.ANIMATOR_DURATION_SCALE,
                    0);
        }
    }

**Comment by Pulimet** [comment]
Thank you. 
I will check it ASAP.

**Comment by Pulimet** [comment]
You was right, as you said when animation in developer options is off the toast wasn't show.
I've fixed it version 1.4.
Thank you again!
